def image

pipeline {
 
    agent any
    stages { 
    
	      stage('Run test') {

              agent {
                  docker 'node:9-alpine'			    
			   }
             environment {
                    npm_config_cache = 'npm-cache'
             }
           
            steps {
                   
                 dir("$WORKSPACE/cidr_convert_api/node") {
                    sh 'npm install '
                     sh 'npm run test '
                    echo "Running Test Complete"
                 } 
			  } 
        }	   
			 
        stage('BuildImage') {                 
            steps { 
                script {
                    image = docker.build("obinnadock/wizeline-obinna-agim", "$WORKSPACE/cidr_convert_api/node")
                }                
            }
        }   
       
        stage('Push') {                 
            steps { 
                script {
                    withDockerRegistry([credentialsId: "dockerhub", url: "https://registry.hub.docker.com" ]) {        
                        image.push("$BUILD_NUMBER")
                    }     
                }
            }
     }
}

