def image

pipeline {

 environment {
    registry = "wizelinedevops/obinna-agim"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
    agent any
    stages {
	 
	     
        stage('BuildImage') {                 
            steps { 
                script {
                    image = docker.build("wizeline-obinna-agim:latest", "$WORKSPACE/cidr_convert_api/node")
                }                
            }
        }   
       
        stage('Push') {                 
            steps { 
                script {
                    withDockerRegistry([credentialsId: "dockerhub", url: "https://registry.hub.docker.com/r/obinnadock/wizeline-obinna-agim" ]) {        
                        image.push()
                    }     
                }
            }
        }
    }
}
		 