def image

pipeline {
 
    agent any
    stages {  
    
        
        stage('BuildImage') {                 
            steps { 
                script {
                    image = docker.build("obinnadock/wizeline-obinna-agim", "$WORKSPACE/cidr_convert_api/node")
                }                
            }
        }   
       
        stage('Push') {                 
            steps { 
                script {
                    withDockerRegistry([credentialsId: "dockerhub", url: "https://registry.hub.docker.com" ]) {        
                        image.push("$BUILD_NUMBER")
                    }     
                }
            }
        }
     }
}

 
